# ===== Server =====
server.port=8081

# ===== OPTION 1 : Base de données en fichier local (Idéal pour Tester sans rien installer) =====
# Au lieu d'un fichier .json (trop compliqué avec Spring JPA), on utilise un fichier de BDD H2.
# Ça va créer un fichier "database.mv.db" directement dans le dossier du projet !
spring.datasource.url=jdbc:h2:file:./database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ===== OPTION 2 : Base de données réelle (MySQL) quand vous serez prêt =====
# Décommentez ceci et commentez l'Option 1 pour passer en vrai SQL :
# spring.datasource.url=jdbc:mysql://localhost:3306/enicar_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=  
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Logs =====
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Sécurité (JWT) =====
app.jwt.secret=enicar-connect-secret-key-2026-very-long-secure-random-string-minimum-256-bits
app.jwt.expiration-ms=86400000

# ===== CORS (URL du Frontend) =====
app.cors.allowed-origins=http://localhost:4200
